# Copyright 2025 VDURA Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# PanFS CSI Driver details
csiPanFSDriver:
  # -- Namespace where the PanFS CSI driver is deployed
  namespace: csi-panfs

# -- Allowed topologies for volume provisioning
# This can be used to restrict volume provisioning to specific nodes or zones
# based on node labels. Uncomment and modify the example below as needed.
# If left empty, no topology constraints will be applied.
allowedTopologies: {}
  # - matchLabelExpressions:
  #   - key: node.kubernetes.io/csi-panfs.panfs.ready
  #     values:
  #       - "true"

# PanFS Realm Endpoint Configuration
realm:
  # -- Endpoint address for the backend PanFS realm
  address: ""
  # -- Username for the PanFS backend realm
  username: ""
  # -- Password for the PanFS backend realm
  password: ""
  # -- Private key for the PanFS backend realm
  privateKey: ""
  # -- Private Key Passphrase
  privateKeyPassphrase: ""

  # -- KMIP configuration data for volume encryption key management
  kmipConfigData: ""

# -- Whether to set current storage class default for the cluster or not
setAsDefaultStorageClass: false

# -- Allow volume expansion for realms
allowVolumeExpansion: true

# -- Default reclaim policy for volumes
# @default -- `Delete`
volumeReclaimPolicy: Delete # Options: Retain, Delete

# -- Default volume binding mode
volumeBindingMode: WaitForFirstConsumer # Options: Immediate, WaitForFirstConsumer

# -- Optional storage class parameters
# @default -- `{...}`
parameters:
  panfs.csi.vdura.com/bladeset: "Set 1"
  panfs.csi.vdura.com/recoverypriority: "50"
  panfs.csi.vdura.com/efsa: "retry"
  panfs.csi.vdura.com/layout: "raid6+"
  panfs.csi.vdura.com/maxwidth: 3
  panfs.csi.vdura.com/stripeunit: "64k"
  panfs.csi.vdura.com/rgwidth: 3
  panfs.csi.vdura.com/rgdepth: 2

  panfs.csi.vdura.com/operm: "all"

  # panfs.csi.vdura.com/volservice: "volserviceid"
  panfs.csi.vdura.com/description: "PanFS CSI Storage Class"

  # panfs.csi.vdura.com/user: username
  # panfs.csi.vdura.com/group: groupname
  # panfs.csi.vdura.com/uperm: "all"
  # panfs.csi.vdura.com/gperm: "write-execute"
  # panfs.csi.vdura.com/operm: "read-write"

  # Enable/Disable E2EE for volumes created with this StorageClass
  # Set to "on" to enable encryption, "off" to disable encryption
  # If enabled, please ensure that KMIP server connection details are provided in the Secret used
  panfs.csi.vdura.com/encryption: "off"

mountOptions: []